exchange: binance

trading:
  symbol: "BTC/USDT"
  timeframe: "1d"
  duration_limit: 3000 #500 timeframes of data
  initial_balance: 1000   # USD
  trade_fraction: 1.0     # fraction of capital per trade (1.0 = all-in)

strategy:
  mca:
    short_window: 20
    long_window: 100

plotting:
  plot_signals: true
  plot_equity: true