exchange: binance

trading:
  symbol: "SOL/USDT"
  timeframe: "1d"
  duration_limit: 3000 #500 timeframes of data
  initial_balance: 1000   # USD
  trade_fraction: 1.0    # fraction of capital per trade (1.0 = all-in)

strategy:
  mca:
    short_window: 20
    long_window: 100

  mca_dynamic_stoploss:
    short_window: 20
    long_window: 100

  mca_guarded:
    short_window: 20
    long_window: 100
    trend_filter_window: 200
    stop_loss_pct: 0.02
    take_profit_pct: 0.04

plotting:
  plot_signals: true
  plot_equity: true